src/S3Train.Web/Areas/Admin/Controllers/NhaCungCapsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using S3Train.Domain;

namespace S3Train.Web.Areas.Admin.Controllers
{
    public class NhaCungCapsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Admin/NhaCungCaps
        public ActionResult Index(int? page)
        {
            int pageNumber = (page ?? 1);
            int pageSize = 10;
            return View(db.NhaCungCaps.ToList().OrderBy(t => t.TenNCC).ToPagedList(pageNumber, pageSize));
        }

        // GET: Admin/NhaCungCaps/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhaCungCap nhaCungCap = db.NhaCungCaps.Find(id);
            if (nhaCungCap == null)
            {
                return HttpNotFound();
            }
            return View(nhaCungCap);
        }

        // GET: Admin/NhaCungCaps/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/NhaCungCaps/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,TenNCC,DiaChi,Email,SDT,ThongTinThem")] NhaCungCap nhaCungCap)
        {
            if (ModelState.IsValid)
            {
                nhaCungCap.Id = Guid.NewGuid();
                db.NhaCungCaps.Add(nhaCungCap);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(nhaCungCap);
        }

        // GET: Admin/NhaCungCaps/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhaCungCap nhaCungCap = db.NhaCungCaps.Find(id);
            if (nhaCungCap == null)
            {
                return HttpNotFound();
            }
            return View(nhaCungCap);
        }

        // POST: Admin/NhaCungCaps/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,TenNCC,DiaChi,Email,SDT,ThongTinThem")] NhaCungCap nhaCungCap)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nhaCungCap).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(nhaCungCap);
        }

        // GET: Admin/NhaCungCaps/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhaCungCap nhaCungCap = db.NhaCungCaps.Find(id);
            if (nhaCungCap == null)
            {
                return HttpNotFound();
            }
            return View(nhaCungCap);
        }

        // POST: Admin/NhaCungCaps/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            NhaCungCap nhaCungCap = db.NhaCungCaps.Find(id);
            db.NhaCungCaps.Remove(nhaCungCap);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

src/S3Train.Web/Areas/Admin/Views/NhaCungCaps/Create.cshtml
@model S3Train.Domain.NhaCungCap

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/SP.cshtml";
}



@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Thêm mới Nhà cung cấp</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Tên", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.TextBoxFor(model => model.TenNCC, new { @class = "form-control"  })
                @Html.ValidationMessageFor(model => model.TenNCC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Địa chỉ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.TextBoxFor(model => model.DiaChi, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Email", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.TextBoxFor(model => model.Email, new { @class = "form-control"  })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Số điện thoại", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.TextBoxFor(model => model.SDT, new { @class = "form-control"  })
                @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Thông tin thêm", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.TextAreaFor(model => model.ThongTinThem, new { @class = "form-control"  })
                @Html.ValidationMessageFor(model => model.ThongTinThem, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm" class="btn btn-primary mb-1" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại", "Index")
</div>

src/S3Train.Web/Areas/Admin/Views/NhaCungCaps/Delete.cshtml
@model S3Train.Domain.NhaCungCap

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/SP.cshtml";
}
<h3 style="color:red">Bạn có chắc muốn xóa @Model.TenNCC này?</h3>
<div>
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-danger mb-1" /> |
            @Html.ActionLink("Quay lại", "Index")
        </div>
    }
</div>

src/S3Train.Web/Areas/Admin/Views/NhaCungCaps/Details.cshtml
@model S3Train.Domain.NhaCungCap

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/LayoutAdmin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>NhaCungCap</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenNCC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenNCC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DiaChi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SDT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SDT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ThongTinThem)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ThongTinThem)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

src/S3Train.Web/Areas/Admin/Views/NhaCungCaps/Edit.cshtml
@model S3Train.Domain.NhaCungCap

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/SP.cshtml";
}

<h2>Chỉnh sửa</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.Label("Tên", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.TextBoxFor(model => model.TenNCC, new { @class = "form-control"  })
                @Html.ValidationMessageFor(model => model.TenNCC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Địa chỉ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.TextBoxFor(model => model.DiaChi, new { @class = "form-control"  })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Email", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.TextBoxFor(model => model.Email, new { @class = "form-control"  })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Số điện thoại", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.TextBoxFor(model => model.SDT, new { @class = "form-control"  })
                @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Thông tin thêm", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.TextAreaFor(model => model.ThongTinThem, new { @class = "form-control"  })
                @Html.ValidationMessageFor(model => model.ThongTinThem, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-primary mb-1" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

src/S3Train.Web/Areas/Admin/Views/NhaCungCaps/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model PagedList.PagedList<S3Train.Domain.NhaCungCap>

@{
                /**/

                ViewBag.Title = "Index";
                Layout = "~/Areas/Admin/Views/Shared/SP.cshtml";
}

<h2>Danh sách Nhà cung cấp</h2>

<p class="btn btn-success mb-1" type="button">
    @Html.ActionLink("Thêm mới nhà cung cấp", "Create")
</p>
<br />
<br />

<div class="col-xl-12 col-lg-7 mb-4">
    <table class="table table-bordered">
        <thead class="thead-light">
            <tr>
                <th>
                    Tên 
                </th>
                <th>
                    Địa chỉ
                </th>
                <th>
                    Email
                </th>
                <th>
                    SĐT
                </th>
                <th>
                    Thông tin thêm
                </th>
                <th></th>
            </tr>
        </thead>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.TenNCC)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DiaChi)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SDT)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ThongTinThem)
                </td>
                <td>
                    <a href="@Url.Action("Edit", "NhaCungCaps", new { id = item.Id })" class="btn btn-warning btn-sm"><i class="fas fa-pen" aria-hidden="true"></i></a>
                    <a href="@Url.Action("Delete", "NhaCungCaps", new { id = item.Id })" class="btn btn-danger btn-sm"><i class="fas fa-trash" aria-hidden="true"></i></a>
                </td>
            </tr>
        }

    </table>
</div>

@*Create page link*@
    Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
    <div class="MenuPage">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
    </div>
    <style>
        .MenuPage li {
            display: inline;
        }
    </style>