src/S3Train.Web/Areas/Admin/Controllers/SanPhams1Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using S3Train.Domain;

namespace S3Train.Web.Areas.Admin.Controllers
{
    public class SanPhams1Controller : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Admin/SanPhams1
        public ActionResult Index(int? page, string search)
        {
            
            int pageNumber = (page ?? 1);
            int pageSize = 20;
            if (search == null)
            {
                var sanPhams = db.SanPhams.Include(s => s.LoaiSanPham).Include(s => s.NgonNgu).Include(s => s.NhaCungCap).Include(s => s.NhaSanXuat).Where(s => s.LoaiSanPham.PhanLoai.TenPhanLoai == "Văn Phòng Phẩm");
                return View(sanPhams.ToList().OrderBy(t => t.NgayCapNhat).ToPagedList(pageNumber, pageSize));
            }
            else
            {
                var sanPhams = db.SanPhams.Include(s => s.LoaiSanPham).Include(s => s.NgonNgu).Include(s => s.NhaCungCap).Include(s => s.NhaSanXuat).Where(s => s.LoaiSanPham.PhanLoai.TenPhanLoai == "Văn Phòng Phẩm" && (s.TenSP.Contains(search)||s.TacGia.Contains(search)));
                return View(sanPhams.ToList().OrderBy(t => t.NgayCapNhat).ToPagedList(pageNumber, pageSize));

            }

        }

        // GET: Admin/SanPhams1/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // GET: Admin/SanPhams1/Create
        public ActionResult Create()
        {
            ViewBag.MaLoai = new SelectList(db.LoaiSanPhams, "Id", "TenLoai");
            ViewBag.MaNN = new SelectList(db.NgonNgus, "Id", "TenNN");
            ViewBag.MaNCC = new SelectList(db.NhaCungCaps, "Id", "TenNCC");
            ViewBag.MaNSX = new SelectList(db.NhaSanXuats, "Id", "TenNSX");
            return View();
        }

        // POST: Admin/SanPhams1/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,TenSP,TacGia,Gia,HinhAnh,TrongLuong,SoLuong,SoTrang,KichThuoc,GhiChu,ChatLuong,MauSac,NgayTao,NgayCapNhat,TrangThai,MaNN,MaNSX,MaNCC,MaLoai,LuotXem")] SanPham sanPham, HttpPostedFileBase fileUpload)
        {
            ViewBag.MaLoai = new SelectList(db.LoaiSanPhams, "Id", "TenLoai", sanPham.MaLoai);
            ViewBag.MaNN = new SelectList(db.NgonNgus, "Id", "TenNN", sanPham.MaNN);
            ViewBag.MaNCC = new SelectList(db.NhaCungCaps, "Id", "TenNCC", sanPham.MaNCC);
            ViewBag.MaNSX = new SelectList(db.NhaSanXuats, "Id", "TenNSX", sanPham.MaNSX);
            var nn = db.NgonNgus.Where(t => t.TenNN == "Việt Nam").Select(t => t.Id).SingleOrDefault();
            if (fileUpload == null)
            {
                ViewBag.Notification = "Chọn ảnh";
                return View();
            }
            if (ModelState.IsValid)
            {
                //Luu ten file
                var fileName = Path.GetFileName(fileUpload.FileName);
                //Luu duong dan
                var path = Path.Combine(Server.MapPath("~/ImagePD"), fileName);
                //KT HINH ANH TON TAI CHUA
                if (System.IO.File.Exists(path))
                {
                    ViewBag.Notification = "Ảnh bị trùng ";
                }
                else
                {
                    fileUpload.SaveAs(path);
                }
                sanPham.Id = Guid.NewGuid();
                sanPham.HinhAnh = fileName;
                sanPham.MaNN = nn;
                sanPham.NgayTao = DateTime.Today;
                sanPham.LuotXem = 0;
                sanPham.TrangThai = true;
                db.SanPhams.Add(sanPham);
                db.SaveChanges();
                return RedirectToAction("Index");
            }


            return View(sanPham);
        }

        // GET: Admin/SanPhams1/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaLoai = new SelectList(db.LoaiSanPhams, "Id", "TenLoai", sanPham.MaLoai);
            ViewBag.MaNN = new SelectList(db.NgonNgus, "Id", "TenNN", sanPham.MaNN);
            ViewBag.MaNCC = new SelectList(db.NhaCungCaps, "Id", "TenNCC", sanPham.MaNCC);
            ViewBag.MaNSX = new SelectList(db.NhaSanXuats, "Id", "TenNSX", sanPham.MaNSX);
            return View(sanPham);
        }

        // POST: Admin/SanPhams1/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,TenSP,TacGia,Gia,HinhAnh,TrongLuong,SoLuong,SoTrang,KichThuoc,GhiChu,ChatLuong,MauSac,NgayTao,NgayCapNhat,TrangThai,MaNN,MaNSX,MaNCC,MaLoai,LuotXem")] SanPham sanPham, HttpPostedFileBase fileUpload)
        {
            if (ModelState.IsValid)
            {
                if (fileUpload != null)
                {
                    //Luu ten file
                    var fileName = Path.GetFileName(fileUpload.FileName);
                    //Luu duong dan
                    var path = Path.Combine(Server.MapPath("~/ImagePD"), fileName);
                    //KT HINH ANH TON TAI CHUA
                    if (System.IO.File.Exists(path))
                    {
                        ViewBag.Notification = "Hình ảnh đã tồn tại";
                    }
                    else
                    {
                        fileUpload.SaveAs(path);
                    }
                    sanPham.HinhAnh = fileName;
                }
                var l = db.NgonNgus.Where(n => n.TenNN == "Việt Nam").Select(n => n.Id).FirstOrDefault();
                sanPham.LuotXem = 0;
                sanPham.MaNN = l;
                db.Entry(sanPham).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaLoai = new SelectList(db.LoaiSanPhams, "Id", "TenLoai", sanPham.MaLoai);
            ViewBag.MaNN = new SelectList(db.NgonNgus, "Id", "TenNN", sanPham.MaNN);
            ViewBag.MaNCC = new SelectList(db.NhaCungCaps, "Id", "TenNCC", sanPham.MaNCC);
            ViewBag.MaNSX = new SelectList(db.NhaSanXuats, "Id", "TenNSX", sanPham.MaNSX);
            return View(sanPham);
        }

        // GET: Admin/SanPhams1/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // POST: Admin/SanPhams1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            SanPham sanPham = db.SanPhams.Find(id);
            db.SanPhams.Remove(sanPham);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

src/S3Train.Web/Areas/Admin/Views/SanPhams1/Create.cshtml
@model S3Train.Domain.SanPham

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/SP.cshtml";
}

@using (Html.BeginForm("Create", "SanPhams1", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Thêm mới văn phòng phẩm</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Tên văn phòng phẩm", htmlAttributes: new { @class = "control-label col-md-5" })
            <div class="col-md-6">
                @Html.TextBoxFor(model => model.TenSP, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TenSP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Tác giả", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.TextBoxFor(model => model.TacGia, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TacGia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Gía", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.TextBoxFor(model => model.Gia, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Gia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Hình ảnh", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                <input type="file" name="fileUpload" />
                @ViewBag.Notification
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Trọng lượng", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.TextBoxFor(model => model.TrongLuong, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TrongLuong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Chất lượng", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.TextBoxFor(model => model.ChatLuong, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TrongLuong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Màu sắc", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.TextBoxFor(model => model.MauSac, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TrongLuong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Số lượng", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.SoLuong, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SoLuong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Kích thước", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.TextBoxFor(model => model.KichThuoc, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.KichThuoc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Mô tả", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.GhiChu, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GhiChu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Nhà sản xuất", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.DropDownListFor(model => model.MaNSX, ViewBag.MaNSX as SelectList, "---Chọn nhà xuất bản---", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaNSX, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Nhà cung cấp", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.DropDownListFor(model => model.MaNCC, ViewBag.MaNCC as SelectList, "---Chọn nhà cung cấp---", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaNCC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Loại sản phẩm", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.DropDownListFor(model => model.MaLoai, ViewBag.MaLoai as SelectList, "---Chọn nhà loại sách---", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaLoai, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm" class="btn btn-primary mb-1" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại", "Index")
</div>

src/S3Train.Web/Areas/Admin/Views/SanPhams1/Delete.cshtml
@model S3Train.Domain.SanPham

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/SP.cshtml";
}

<h3 style="color:red">Bạn có chắc muốn xóa sản phẩm @Model.TenSP?</h3>
<div>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-danger mb-1" /> |
            @Html.ActionLink("Quay lại", "Index")
        </div>
    }
</div>

src/S3Train.Web/Areas/Admin/Views/SanPhams1/Details.cshtml
@model S3Train.Domain.SanPham

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/LayoutAdmin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>SanPham</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LoaiSanPham.TenLoai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiSanPham.TenLoai)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgonNgu.TenNN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgonNgu.TenNN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NhaCungCap.TenNCC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NhaCungCap.TenNCC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NhaSanXuat.TenNSX)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NhaSanXuat.TenNSX)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenSP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TacGia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TacGia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HinhAnh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HinhAnh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TrongLuong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TrongLuong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoLuong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoTrang)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoTrang)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KichThuoc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KichThuoc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GhiChu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GhiChu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ChatLuong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChatLuong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MauSac)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MauSac)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayTao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayTao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayCapNhat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayCapNhat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TrangThai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TrangThai)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LuotXem)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LuotXem)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

src/S3Train.Web/Areas/Admin/Views/SanPhams1/Edit.cshtml
@model S3Train.Domain.SanPham

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/SP.cshtml";
}

<h2>Chỉnh sửa</h2>

@using (Html.BeginForm("Edit", "SanPhams1", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.Label("Tên", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.TextBoxFor(model => model.TenSP, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TenSP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Tác giả", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.TextBoxFor(model => model.TacGia, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TacGia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Gía", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.TextBoxFor(model => model.Gia, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Gia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Hình ảnh", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.TextBoxFor(model => model.HinhAnh, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.HinhAnh, "", new { @class = "text-danger" })
                <input type="file" name="fileUpload" />
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Trọng lượng", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.TextBoxFor(model => model.TrongLuong, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TrongLuong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Số lượng", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.SoLuong, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SoLuong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Màu sắc", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.TextBoxFor(model => model.MauSac, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MauSac, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Kích thước", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.TextBoxFor(model => model.KichThuoc, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.KichThuoc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Mô tả", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.TextAreaFor(model => model.GhiChu, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GhiChu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgayTao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.NgayTao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayTao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgayCapNhat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.NgayCapNhat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayCapNhat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TrangThai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                <div class="checkbox">
                    @Html.EditorFor(model => model.TrangThai)
                    @Html.ValidationMessageFor(model => model.TrangThai, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Nhà sản xuất", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.DropDownList("MaNSX", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaNSX, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Nhà cung cấp", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.DropDownList("MaNCC", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaNCC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Loại sản phẩm", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.DropDownList("MaLoai", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaLoai, "", new { @class = "text-danger" })
            </div>
        </div>
        @*<div class="form-group">
                @Html.LabelFor(model => model.LuotXem, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.LuotXem, new { @class = "form-control"  })
                    @Html.ValidationMessageFor(model => model.LuotXem, "", new { @class = "text-danger" })
                </div>
            </div>*@


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-primary mb-1" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại", "Index")
</div>

src/S3Train.Web/Areas/Admin/Views/SanPhams1/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model PagedList.PagedList<S3Train.Domain.SanPham>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/SP.cshtml";
}

<h2>Danh mục Văn phòng phẩm</h2>

<p class="btn btn-success mb-1">
    @Html.ActionLink("Thêm mới văn phòng phẩm", "Create")
</p>
<br />
<br />
@using (Html.BeginForm("Index", "SanPhams1", FormMethod.Get))
{
    @Html.TextBox("search")
    <input type="submit" style="color:white" value="Tìm Kiếm">
}
<br />
@using (Html.BeginForm("Index", "SanPhams1", FormMethod.Get))
{
    <div class="col-xl-12 col-lg-7 mb-4">
        <table class="table table-bordered">
            <thead class="thead-light">
                <tr>
                    <th>
                        Hình ảnh
                    </th>
                    <th>
                        Tên sản phẩm
                    </th>
                    <th>
                        Màu sắc
                    </th>
                    <th>
                        Tác giả
                    </th>
                    <th>
                        Nhà sản xuất
                    </th>
                    <th>
                        Gía
                    </th>
                    <th>
                        Loại sản phẩm
                    </th>
                    <th></th>
                </tr>
            </thead>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <img src="@Url.Content("~/ImagePD/" + item.HinhAnh)" width="50" height="50" />
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TenSP)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MauSac)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TacGia)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NhaSanXuat.TenNSX)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Gia)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LoaiSanPham.TenLoai)
                    </td>
                    <td>
                        <a href="@Url.Action("Edit", "SanPhams1", new { id = item.Id })" class="btn btn-warning btn-sm"><i class="fas fa-pen" aria-hidden="true"></i></a>
                        @*<a href="@Url.Action("Details", "SanPhams", new { id = item.Id })" class="btn btn-info btn-sm"><i class="fas fa-info-circle" aria-hidden="true"></i></a>*@
                        <a href="@Url.Action("Delete", "SanPhams1", new { id = item.Id })" class="btn btn-danger btn-sm"><i class="fas fa-trash" aria-hidden="true"></i></a>

                    </td>
                </tr>
            }

        </table>
    </div>
}
    @*Create page link*@
    Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
    <div class="MenuPage">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
    </div>
    <style>
        .MenuPage li {
            display: inline;
        }
    </style>