src/S3Train.Web/Models/CSProductViewModel.cs
using System;

namespace S3Train.Web.Models
{
    public class CSProductViewModel
    {
        public Guid Id { get; set; }
        public string ImagePath { get; set; }
        public string NameProduct { get; set; }
        public decimal DisplayPrice { get; set; }
        public int Grouping { get; set; }
    }
}

src/S3Train.Web/Models/HomeViewModel.cs
using System.Collections.Generic;
using System.Linq;


namespace S3Train.Web.Models
{
    public class HomeViewModel
    {
        public IList<SliderItemViewModel> SliderItems { get; set; }
        public IEnumerable<IGrouping<int, ProductViewModel>> NewProducts { get; set; }
        public IEnumerable<IGrouping<int, CSProductViewModel>> CSProducts { get; set; }
        public IEnumerable<IGrouping<int, VPPModels>> VPPProducts { get; set; }
        public IEnumerable<IGrouping<int, PromotionProductViewModel>> PromotionProducts { get; set; }
        public IList<CategoryViewModel> ProductsByCategory { get; set; }
        public IList<ProductViewModel> newProducts { get; set; }
        public IList<CSProductViewModel> csProducts { get; set; }
        public IList<VPPModels> vppProducts { get; set; }
        public IList<PromotionProductViewModel> bestSellerProducts { get; set; }
        public IList<ProductsSearchForNameViewModel> productsSearchForName { get; set; }
        public IList<OrderProViewModel> OrderProViewModel { get; set; }
    }
}

src/S3Train.Web/Models/ProductViewModel.cs
using System;


namespace S3Train.Web.Models
{
    public class ProductViewModel
    {
        public Guid Id { get; set; }
        public string ImagePath { get; set; }
        public string NameProduct { get; set; }
        public string Summary { get; set; }
        public decimal DisplayPrice { get; set; }
        public string Barcode { get; set; }
        public int Rating { get; set; }
        public int Grouping { get; set; }
    }
}

src/S3Train.Web/Models/PromotionProductViewModel.cs
using S3Train.DTOs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace S3Train.Web.Models
{
    public class PromotionProductViewModel
    {
        public Guid Id { get; set; }
        public string ImagePath { get; set; }
        public string NameProduct { get; set; }
        public decimal DisplayPrice { get; set; }
        public decimal Price { get; set; }
        public double PromotionPercent { get; set; }
        public int Grouping { get; set; }
    }
}

src/S3Train.Web/Controllers/HomeController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using S3Train.Contract;
using S3Train.Domain;
using S3Train.Web.Models;
using S3Train.DTOs;

namespace S3Train.Controllers
{
    public class HomeController : Controller
    {
        private readonly IProductService _newProductService;
        private readonly IProductAdvertisementService _productAdvertisementService;
        private readonly ICategoryService _categoryService;
        private readonly ICSProductService _cSProductService;
        private readonly IPromotionDetailService _promotionProductService;
        private readonly IVPPService _vppService;

        public HomeController(IProductService newProductService, IProductAdvertisementService productAdvertisementService, ICategoryService categoryService, ICSProductService cSProductSerVice, IPromotionDetailService promotionDetailService, IVPPService vPPService)
        {
            _newProductService = newProductService;
            _productAdvertisementService = productAdvertisementService;
            _categoryService = categoryService;
            _cSProductService = cSProductSerVice;
            _promotionProductService = promotionDetailService;
            _vppService = vPPService;
        }

        public ActionResult Index()
        {
            var model = new HomeViewModel
            {
                SliderItems = GetHomeSlider(_productAdvertisementService.GetSliderItems()),
                NewProducts = GetHomeNewProducts(_newProductService.GetNewProductItems()),
                CSProducts = GetHomeCSProducts(_cSProductService.GetCSProductItems()),
                PromotionProducts = GetHomeBestSellerProducts(_promotionProductService.GetPromotionDetail()),
                VPPProducts = GetVPP(_vppService.GetVPP())

            };

            return View(model);
        }

        private static IEnumerable<IGrouping<int, VPPModels>> GetVPP(IList<ProductDTO> products)
        {
            return products.Select((x, i) => new VPPModels
            {
                Id = x.Id,
                ImagePath = x.HinhAnh,
                NameProduct = x.TenSP,
                UpdatedDate = x.NgayCapNhat,
                DisplayPrice = x.Gia,
                Grouping = i / 4
            }).GroupBy(e => e.Grouping).ToList();
        }

        private static IEnumerable<IGrouping<int, ProductViewModel>> GetHomeNewProducts(IList<ProductDTO> products)
        {
            return products.Select((x, i) => new ProductViewModel
            {
                Id = x.Id,
                ImagePath = x.HinhAnh,
                NameProduct = x.TenSP,
                DisplayPrice = x.Gia,
                Grouping = i / 4
            }).GroupBy(e => e.Grouping).ToList();
        }

        private static IEnumerable<IGrouping<int, CSProductViewModel>> GetHomeCSProducts(IList<ProductDTO> products)
        {
            return products.Select((x, i) => new CSProductViewModel
            {
                Id = x.Id,
                ImagePath = x.HinhAnh,
                NameProduct = x.TenSP,
                DisplayPrice = x.Gia,
                Grouping = i / 4
            }).GroupBy(e => e.Grouping).ToList();
        }

        private static IEnumerable<IGrouping<int, PromotionProductViewModel>> GetHomeBestSellerProducts(IList<ProductDTO> promotionDetail)
        {
            return promotionDetail.Select((x, i) => new PromotionProductViewModel
            {
                Id = x.ProductId,
                ImagePath = x.HinhAnh,
                NameProduct = x.TenSP,
                Price = x.Gia,
                PromotionPercent = x.KhuyenMais.First().PhanTramKM,
                Grouping = i / 4
            }).GroupBy(e => e.Grouping).ToList();
        }

        private static IList<SliderItemViewModel> GetHomeSlider(IList<ManHinhTrangChu> productAds)
        {
            return productAds.Select(x => new SliderItemViewModel
            {
                ProductId = x.MaSP,
                ImagePath = x.ImagePath,
                Title = x.Title,
                Description = x.Description,
                EventUrl = x.EventUrl,
            }).ToList();
        }

        private static IList<CategoryViewModel> GetHomeCategory(IList<LoaiSanPham> category)
        {
            return category.Select(x => new CategoryViewModel
            {
                NameCategory = x.TenLoai
            }).ToList();

        }



    }
}

src/S3Train.Web/Controllers/ListOfProductsController.cs
using S3Train.Contract;
using S3Train.DTOs;
using S3Train.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace S3Train.Web.Controllers
{
    public class ListOfProductsController : Controller
    {
        private readonly IProductService _newProductsService;
        private readonly ICSProductService _cSProductsService;
        private readonly IPromotionDetailService _bestSellerProductsService;
        private readonly IVPPService _vppProductsService;


        public ListOfProductsController(IProductService newProductsService,  
            ICSProductService cSProductsSerVice, IPromotionDetailService bestSellerProductsService,
            IVPPService vppProductsService)
        {
            _newProductsService = newProductsService;
            _cSProductsService = cSProductsSerVice;
            _bestSellerProductsService = bestSellerProductsService;
            _vppProductsService = vppProductsService;
        }

        //GET: List VPP
        public ActionResult VPP(int page = 1, int pagesize = 20)
        {
            int totalRecord = 0;

            var model = new HomeViewModel
            {
                vppProducts = GetVPP(_vppProductsService.GetVPP(), ref totalRecord, page, pagesize),
            };

            ViewBag.ToTal = totalRecord;
            ViewBag.Page = page;

            int maxPage = 5;
            int totalPage = 0;
            totalPage = (int)Math.Ceiling(((double)totalRecord / (double)pagesize));

            ViewBag.TotalPage = totalPage;
            ViewBag.MaxPage = maxPage;
            ViewBag.First = 1;
            ViewBag.Last = totalPage;
            ViewBag.Next = page + 1;
            ViewBag.Pre = page - 1;

            return View(model);
        }

        // GET: ListOfProducts
        public ActionResult NewProducts(int page = 1, int pagesize = 20)
        {
            int totalRecord = 0;

            var model = new HomeViewModel
            {
                newProducts = GetNewProducts(_newProductsService.GetNewProductItems(), ref totalRecord, page, pagesize),
            };

            ViewBag.ToTal = totalRecord;
            ViewBag.Page = page;

            int maxPage = 5;
            int totalPage = 0;
            totalPage = (int)Math.Ceiling(((double)totalRecord / (double)pagesize));

            ViewBag.TotalPage = totalPage;
            ViewBag.MaxPage = maxPage;
            ViewBag.First = 1;
            ViewBag.Last = totalPage;
            ViewBag.Next = page + 1;
            ViewBag.Pre = page - 1;

            return View(model);
        }

        public ActionResult cSProducts(int page = 1, int pagesize = 20)
        {
            int totalRecord = 0;

            var csproducts = new HomeViewModel
            {
                csProducts = GetCSProducts(_cSProductsService.GetCSProductItems(), ref totalRecord, page, pagesize),
            };

            ViewBag.ToTal = totalRecord;
            ViewBag.Page = page;

            int maxPage = 5;
            int totalPage = 0;
            totalPage = (int)Math.Ceiling(((double)totalRecord / (double)pagesize));

            ViewBag.TotalPage = totalPage;
            ViewBag.MaxPage = maxPage;
            ViewBag.First = 1;
            ViewBag.Last = totalPage;
            ViewBag.Next = page + 1;
            ViewBag.Pre = page - 1;

            return View(csproducts);
        }

        public ActionResult bestSellerProducts(int page = 1, int pagesize = 20)
        {
            int totalRecord = 0;
            var csproducts = new HomeViewModel
            {
                bestSellerProducts = GetBestSellerProducts(_bestSellerProductsService.GetPromotionDetail(), ref totalRecord, page, pagesize),
            };

            ViewBag.ToTal = totalRecord;
            ViewBag.Page = page;

            int maxPage = 5;
            int totalPage = 0;
            totalPage = (int)Math.Ceiling(((double)totalRecord / (double)pagesize));

            ViewBag.TotalPage = totalPage;
            ViewBag.MaxPage = maxPage;
            ViewBag.First = 1;
            ViewBag.Last = totalPage;
            ViewBag.Next = page + 1;
            ViewBag.Pre = page - 1;

            return View(csproducts);
        }

        private static IList<VPPModels> GetVPP(IList<ProductDTO> products, ref int totalRecord, int page = 1, int pagesize = 20)
        {
            var totalPro = products.Select((x) => new VPPModels
            {
                Id = x.Id,
                ImagePath = x.HinhAnh,
                NameProduct = x.TenSP,
                DisplayPrice = x.Gia,
            });

            var model = totalPro.OrderBy(x => x.NameProduct).Skip((page - 1) * pagesize).Take(pagesize).ToList();
            totalRecord = totalPro.Count();

            return model;
        }

        private static IList<ProductViewModel> GetNewProducts(IList<ProductDTO> products, ref int totalRecord, int page = 1, int pagesize = 20)
        {
            var totalPro = products.Select((x) => new ProductViewModel
            {
                Id = x.Id,
                ImagePath = x.HinhAnh,
                NameProduct = x.TenSP,
                DisplayPrice = x.Gia,
            });

            var model = totalPro.OrderBy(x => x.NameProduct).Skip((page - 1) * pagesize).Take(pagesize).ToList();
            totalRecord = totalPro.Count();

            return model;
        }

        private static IList<CSProductViewModel> GetCSProducts(IList<ProductDTO> products, ref int totalRecord, int page = 1, int pagesize = 20)
        {
            var totalPro = products.Select((x) => new CSProductViewModel
            {
                Id = x.Id,
                ImagePath = x.HinhAnh,
                NameProduct = x.TenSP,
                DisplayPrice = x.Gia,
            });

            var model = totalPro.OrderBy(x => x.NameProduct).Skip((page - 1) * pagesize).Take(pagesize).ToList();
            totalRecord = totalPro.Count();

            return model;
        }

        private static IList<PromotionProductViewModel> GetBestSellerProducts(IList<ProductDTO> promotionDetail, ref int totalRecord, int page = 1, int pagesize = 20)
        {
            var totalPro = promotionDetail.Select((x) => new PromotionProductViewModel
            {
                Id = x.ProductId,
                ImagePath = x.HinhAnh,
                NameProduct = x.TenSP,
                DisplayPrice = x.Gia,
                PromotionPercent = x.KhuyenMais.FirstOrDefault().PhanTramKM,
                Price = x.Gia,
            });

            var model = totalPro.OrderBy(x => x.NameProduct).Skip((page - 1) * pagesize).Take(pagesize).ToList();
            totalRecord = totalPro.Count();

            return model;
        }
    }
}

src/S3Train.Web/Controllers/ProductController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using S3Train.Contract;
using S3Train.Domain;
using S3Train.Web.Models;
using System;
using S3Train.DTOs;

namespace S3Train.Web.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductDetailService _detailProductService;

        public ProductController(IProductDetailService detailProductService)
        {
            _detailProductService = detailProductService;

        }

        public ActionResult Detail(Guid id)
        {
            var prodDetail = _detailProductService.GetProductDetail(id);
            var productDetailViewModel = new ProductDetailViewModel();

                if(prodDetail.KhuyenMais.Count() != 0)
                {
                    productDetailViewModel = new ProductDetailViewModel
                    {

                        Id = prodDetail.Id,
                        Name = prodDetail.TenSP,
                        ImagePath = prodDetail.HinhAnh,
                        DisplayPrice = prodDetail.Gia,
                        Price = prodDetail.Gia,
                        Summary = prodDetail.GhiChu,
                        NCC = prodDetail.NhaCungCap.TenNCC,
                        CategoryName = prodDetail.LoaiSanPham.TenLoai,
                        UpdatedDate = prodDetail.NgayCapNhat,
                        Amount = prodDetail.SoLuong,
                        AuthorName = prodDetail.TacGia,
                        PromotionPercent = prodDetail.KhuyenMais.FirstOrDefault().PhanTramKM,
                        NamePublisher = prodDetail.NhaSanXuat.TenNSX,
                        TrongLuong = prodDetail.TrongLuong,
                        KichThuoc = prodDetail.KichThuoc,
                        SoTrang = prodDetail.SoTrang,
                        ChatLuong = prodDetail.ChatLuong,
                        MauSac = prodDetail.MauSac,
                        TenPhanLoai = prodDetail.LoaiSanPham.TenPhanLoai,
                        NgonNgu = prodDetail.NgonNgu.TenNN,
                        RelatedProduct = prodDetail.RelatedProduct.Select(q => new ProductViewModel
                        {
                            Id = q.Id,
                            NameProduct = q.TenSP,
                            ImagePath = q.HinhAnh,
                            DisplayPrice = q.Gia
                        }).ToList()

                    };
                }else
                {
                productDetailViewModel = new ProductDetailViewModel
                {

                    Id = prodDetail.Id,
                    Name = prodDetail.TenSP,
                    ImagePath = prodDetail.HinhAnh,
                    DisplayPrice = prodDetail.Gia,
                    Price = prodDetail.Gia,
                    Summary = prodDetail.GhiChu,
                    AuthorName = prodDetail.TacGia,
                    NamePublisher = prodDetail.NhaSanXuat.TenNSX,
                    NCC = prodDetail.NhaCungCap.TenNCC,
                    CategoryName = prodDetail.LoaiSanPham.TenLoai,
                    UpdatedDate = prodDetail.NgayCapNhat,
                    TrongLuong = prodDetail.TrongLuong,
                    KichThuoc = prodDetail.KichThuoc,
                    SoTrang = prodDetail.SoTrang,
                    ChatLuong = prodDetail.ChatLuong,
                    MauSac = prodDetail.MauSac,
                    Amount = prodDetail.SoLuong,
                    TenPhanLoai = prodDetail.LoaiSanPham.TenPhanLoai,
                    NgonNgu = prodDetail.NgonNgu.TenNN,
                    RelatedProduct = prodDetail.RelatedProduct.Select(q => new ProductViewModel
                    {
                        Id = q.Id,
                        NameProduct = q.TenSP,
                        ImagePath = q.HinhAnh,
                        DisplayPrice = q.Gia
                    }).ToList()

                };
            }
                
            return View(productDetailViewModel);
        }

    }

       
}

src/S3Train.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

src/S3Train.Web/Views/Home/Index.cshtml
@using S3Train.Web.Models;
@model HomeViewModel

@{
    ViewBag.Title = "Home Page";
}


<div class="container">

    @{
        Html.RenderPartial("_HomeSlider", Model.SliderItems);
    }
    <div class="product">

        <!-- Sách mới -->
        <div class="products">
            <h5 class="latest-product">SÁCH MỚI</h5>
            <a class="view-all" href="@Url.Action("NewProducts", "ListOfProducts", null)">XEM THÊM<span></span></a>
        </div>
        <div class="clearfix"> </div>
        <div class="container">
            <div class="row">
                <div class="well">
                    <!-- Carousel ================================================== -->
                    <div id="myCarousel" class="carousel slide">
                        @Html.Partial("_NewProduct", Model.NewProducts)
                        <a class="left carousel-control" href="#myCarousel" data-slide="prev"><i class="fa fa-chevron-left fa-2x"></i></a>
                        <a class="right carousel-control" href="#myCarousel" data-slide="next"><i class="fa fa-chevron-right fa-2x"></i></a>

                    </div><!-- End Carousel -->
                </div><!-- End Well -->
            </div>
        </div>

        <!-- Sách sắp về -->
        <div class="products">
            <h5 class="latest-product">SÁCH SẮP VỀ</h5>
            <a class="view-all" href="@Url.Action("cSProducts", "ListOfProducts", null)">XEM THÊM<span> </span></a>
        </div>
        <div class="clearfix"> </div>

        <div class="container">
            <div class="row">
                <div class="well">
                    <!-- Carousel================================================== -->
                    <div id="myCarousel1" class="carousel slide">
                        @Html.Partial("_CSProduct", Model.CSProducts)
                        <a class="left carousel-control" href="#myCarousel1" data-slide="prev"><i class="fa fa-chevron-left fa-2x"></i></a>
                        <a class="right carousel-control" href="#myCarousel1" data-slide="next"><i class="fa fa-chevron-right fa-2x"></i></a>

                    </div><!-- End Carousel -->
                </div><!-- End Well -->
            </div>
        </div>
        <div class="clearfix"> </div>

        <!-- Sách bán chạy -->
        <div class="products">
            <h5 class="latest-product">SẢN PHẨM BÁN CHẠY</h5>
            <a class="view-all" href="@Url.Action("bestSellerProducts", "ListOfProducts", null)">XEM THÊM<span> </span></a>
        </div>
        <div class="clearfix"> </div>
        <div class="container">
            <div class="row">
                <div class="well">
                    <!-- Carousel
                ================================================== -->
                    <div id="myCarousel2" class="carousel slide">
                        @Html.Partial("_PromotionProduct", Model.PromotionProducts)
                        <a class="left carousel-control" href="#myCarousel2" data-slide="prev"><i class="fa fa-chevron-left fa-2x"></i></a>
                        <a class="right carousel-control" href="#myCarousel2" data-slide="next"><i class="fa fa-chevron-right fa-2x"></i></a>

                    </div><!-- End Carousel -->
                </div><!-- End Well -->
            </div>
        </div>
        <div class="clearfix"> </div>

        <!-- Văn phòng phẩm -->
        <div class="products">
            <h5 class="latest-product">VĂN PHÒNG PHẨM</h5>
            <a class="view-all" href="@Url.Action("VPP", "ListOfProducts", null)">XEM THÊM<span></span></a>
        </div>
        <div class="clearfix"> </div>
        <div class="container">
            <div class="row">
                <div class="well">
                    <!-- Carousel================================================== -->
                    <div id="myCarousel4" class="carousel slide">
                        @Html.Partial("_VPPham", Model.VPPProducts)
                        <a class="left carousel-control" href="#myCarousel4" data-slide="prev"><i class="fa fa-chevron-left fa-2x"></i></a>
                        <a class="right carousel-control" href="#myCarousel4" data-slide="next"><i class="fa fa-chevron-right fa-2x"></i></a>

                    </div><!-- End Carousel -->
                </div><!-- End Well -->
            </div>
        </div>
        <div class="clearfix"> </div>

    </div>
    <div class="clearfix"> </div>

    <script>
    $('#myCarousel').carousel({
        interval: 0
    });
    $('#myCarousel1').carousel({
        interval: 0
    });
    $('#myCarousel2').carousel({
        interval: 0
    });
    $('#myCarousel3').carousel({
        interval: 0
        });
    $('#myCarousel4').carousel({
        interval: 0
    });
    </script>
</div>

src/S3Train.Web/Views/Home/_CSProduct.cshtml
@using S3Train.Web.Models;
@model IEnumerable<IGrouping<int, CSProductViewModel>>
@{
    ViewBag.Title = "_CSProduct";
}

<div class="carousel-inner">
    @{
        foreach (var group in Model)
        {
            var activeClass = group.Key == 0 ? "active" : string.Empty;
            <div class="item @activeClass">
                <div class="row">
                    @foreach (var item in group)
                    {

                        <div class="col-md-3">
                            <div class="thumbnail">

                                <a href="@Url.Action("Detail", "Product",new { @id = item.Id} )">
                                    <img src="@Url.Content("~/ImagePD/"+item.ImagePath)" />
                                </a>
                                <div class="caption">
                                    <a href="@Url.Action("Detail", "Product",new { @id = item.Id} )"><h5>@item.NameProduct</h5></a>
                                    <p><a  class="btn btn-primary" role="button">@item.DisplayPrice</a><a id="btn-add-to-cart1" href="@Url.Action("Detail", "Product", new { @id = item.Id })" style="float:right"  class="btn btn-default" role="button">Xem trước</a></p>
                                </div>

                            </div>
                        </div>

                    }

                </div>
            </div>
        }
    }

</div>

src/S3Train.Web/Views/Home/_NewProduct.cshtml
@using S3Train.Web.Models;
@model IEnumerable<IGrouping<int, ProductViewModel>>
@{
    ViewBag.Title = "_NewProduct";
}
<div class="carousel-inner">
    @{
        foreach (var group in Model)
        {
            var activeClass = group.Key == 0 ? "active" : string.Empty;
            <div class="item @activeClass">
                <div class="row">
                    @foreach (var item in group)
                    {

                        <div class="col-md-3">
                            <div class="thumbnail">

                                <a href="@Url.Action("Detail", "Product",new { @id = item.Id} )">
                                    <img src="@Url.Content("~/ImagePD/"+item.ImagePath)" />
                                </a>
                                <div class="caption">
                                    <a href="@Url.Action("Detail", "Product",new { @id = item.Id} )"><h5>@item.NameProduct</h5></a>
                                    <p><a class="btn btn-primary" role="button">@item.DisplayPrice</a><a id="btn-add-to-cart" data-id="@item.Id" style="float:right"  class="btn btn-default" role="button" onclick="myFunction()">Thêm vào giỏ hàng</a></p>
                                    <div id="snackbar">Add to cart successfully</div>
                                </div>

                            </div>
                        </div>

                    }

                </div>
            </div>
        }
    }

</div>
<script>
    $(document).ready(function () {
        $('.btn-default').click(function () {
            var id = $(this).data("id");
            $.ajax({
                type: "POST",
                url: '/Cart/AddItems',
                data: { Id: id },
                success: function (data) {
                }
            });
        });
    });
    function myFunction() {
      // Get the snackbar DIV
      var x = document.getElementById("snackbar");

      // Add the "show" class to DIV
      x.className = "show";

      // After 3 seconds, remove the show class from DIV
        setTimeout(function () { x.className = x.className.replace("show", ""); }, 5000);
    }
</script>

src/S3Train.Web/Views/Home/_PromotionProduct.cshtml
@using S3Train.Web.Models;
@model IEnumerable<IGrouping<int, PromotionProductViewModel>>
@{
    ViewBag.Title = "_PromotionProduct";
}

<div class="carousel-inner">
    @{
        foreach (var group in Model)
        {
            var activeClass = group.Key == 0 ? "active" : string.Empty;
            <div class="item @activeClass">
                <div class="row">
                    @foreach (var item in group)
                    {

                        <div class="col-md-3">
                            <div class="thumbnail">

                                <a href="@Url.Action("Detail", "Product",new { @id = item.Id} )">
                                    <img src="@Url.Content("~/ImagePD/"+item.ImagePath)" />
                                </a>
                                <div class="caption">
                                    <a href="@Url.Action("Detail", "Product",new { @id = item.Id} )"><h5>@item.NameProduct</h5></a>
                                    <p>
                                        <a id="btn-add-to-cart" class="btn btn-primary" role="button">@(Convert.ToDouble(item.Price) - (Convert.ToDouble(item.Price) * item.PromotionPercent / 100))</a>
                                        <a id="btn-add-to-cart" data-id="@item.Id" style="float:right" class="btn btn-default" role="button" onclick="myFunction()">Thêm vào giỏ hàng</a>
                                    </p>
                                    <div id="snackbar">Add to cart successfully</div>
                                </div>

                            </div>
                        </div>

                    }

                </div>
            </div>
        }
    }

</div>

<script>
    $(document).ready(function () {
        $('.btn-default').click(function () {
            var id = $(this).data("id");
            $.ajax({
                type: "POST",
                url: '/Cart/AddItems',
                data: { Id: id },
                success: function (data) {
                }
            });
        });
    });
    function myFunction() {
        // Get the snackbar DIV
        var x = document.getElementById("snackbar");

        // Add the "show" class to DIV
        x.className = "show";

        // After 3 seconds, remove the show class from DIV
        setTimeout(function () { x.className = x.className.replace("show", ""); }, 5000);
    }
</script>

src/S3Train.Web/Views/Home/_VPPham.cshtml
@using S3Train.Web.Models;
@model IEnumerable<IGrouping<int, VPPModels>>
@{
    ViewBag.Title = "_VPPham";
}
<div class="carousel-inner">
    @{
        foreach (var group in Model)
        {
            var activeClass = group.Key == 0 ? "active" : string.Empty;
            <div class="item @activeClass">
                <div class="row">
                    @foreach (var item in group)
                    {

                        <div class="col-md-3">
                            <div class="thumbnail">

                                <a href="@Url.Action("Detail", "Product",new { @id = item.Id} )">
                                    <img src="@Url.Content("~/ImagePD/"+item.ImagePath)" />
                                </a>
                                <div class="caption">
                                    <a href="@Url.Action("Detail", "Product",new { @id = item.Id} )"><h5>@item.NameProduct</h5></a>
                                    <p>
                                        <a class="btn btn-primary" role="button">@item.DisplayPrice</a>
                                        @if (item.UpdatedDate == null)
                                        {
                                            <a data-id="@item.Id" style="float:right" class="btn btn-default" href="@Url.Action("Detail", "Product", new { @id = item.Id })" role="button" onclick="myFunction()">Xem trước</a>
                                        }
                                        else
                                        {
                                            <a id="btn-add-to-cart" data-id="@item.Id" style="float:right" class="btn btn-default"  role="button" onclick="myFunction()">Thêm vào giỏ hàng</a>

                                        }
                                    </p>
                                    
                                    <div id="snackbar">Add to cart successfully</div>
                                </div>

                            </div>
                        </div>

                    }

                </div>
            </div>
        }
    }

</div>
<script>
    $(document).ready(function () {
        $('.btn-default').click(function () {
            var id = $(this).data("id");
            $.ajax({
                type: "POST",
                url: '/Cart/AddItems',
                data: { Id: id },
                success: function (data) {
                }
            });
        });
    });
    function myFunction() {
      // Get the snackbar DIV
      var x = document.getElementById("snackbar");

      // Add the "show" class to DIV
      x.className = "show";

      // After 3 seconds, remove the show class from DIV
        setTimeout(function () { x.className = x.className.replace("show", ""); }, 5000);
    }
</script>